#!/bin/bash

source go_and_ruby

git submodule init
git submodule status | awk '{print $2}' | xargs -P10 -n1 git submodule update --init --recursive

rm -rf dev_releases
echo $PIPELINE_RELEASE_NAME | bosh create release --with-tarball --force
