#!/bin/bash

source `which go_and_ruby`

SHELL=/bin/bash bundle exec cf_deploy \
  --non-interactive \
  --release-name $RELEASE_NAME \
  --release-repo $RELEASE_REPO \
  --release-ref $RELEASE_REF \
  --infrastructure $INFRASTRUCTURE \
  --deployments-repo $DEPLOYMENTS_REPO \
  --deployment-name $DEPLOYMENT_NAME \
  --rebase
